---
- hosts: all
  become: true

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: name={{ item }} state=latest update_cache=yes
      loop: ["docker-ce"]

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: install docker-compose
      become: True
      shell:
        cmd: "sudo curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose "

    - name: install docker-compose
      become: True
      shell:
        cmd: "sudo chmod +x /usr/local/bin/docker-compose"

    - name: build docker image
      become: true
      shell:
        cmd: "sudo docker build -t gestionscolaire:latest --no-cache . -f /home/ubuntu/gestionScolaire/docker/Dockerfile"


    - name: Run container
      become: True
      shell:
        cmd: "sudo docker-compose -f /home/ubuntu/gestionScolaire/docker/docker-compose.yml up -d"